from __future__ import annotations

import os
from pathlib import Path

from vla_skill.constants import (
    DEFAULT_BASE_MODEL_PATH,
    DEFAULT_SEED,
    DEFAULT_SKILL_ROOT,
    MAX_ACTION_DIM,
    MAX_STATE_DIM,
)

_DATA_ROOT = Path(os.environ.get("VLA_DATA_ROOT", os.environ.get("VLA_SKILL_ROOT", Path(__file__).resolve().parents[2])))
DEFAULT_ROUTER_OUTPUT_ROOT = Path(
    os.environ.get("VLA_ROUTER_OUTPUT_ROOT", _DATA_ROOT / "outputs" / "pi05_skill_router_lora")
)
DEFAULT_ROUTER_CE_WEIGHT = 1.0
DEFAULT_ROUTER_FEATURE_HOOK = "pi05_paligemma_with_expert"
DEFAULT_ROUTER_TYPE = "hard_top1"
ROUTER_IMPL_HARD_TOP1 = "hard_top1"
ROUTER_IMPL_LORA_CONTROL = "lora_control"
SUPPORTED_ROUTER_TYPES = (ROUTER_IMPL_HARD_TOP1, ROUTER_IMPL_LORA_CONTROL)
DEFAULT_ROUTER_CONTROL_ADAPTER = "router_control"
DEFAULT_ROUTER_STATE_EMBED_DIM = 64
DEFAULT_ROUTER_HIDDEN_DIM = 256
DEFAULT_LORA_GROUP = "C"

__all__ = [
    "DEFAULT_BASE_MODEL_PATH",
    "DEFAULT_LORA_GROUP",
    "DEFAULT_ROUTER_CE_WEIGHT",
    "DEFAULT_ROUTER_CONTROL_ADAPTER",
    "DEFAULT_ROUTER_FEATURE_HOOK",
    "DEFAULT_ROUTER_HIDDEN_DIM",
    "DEFAULT_ROUTER_OUTPUT_ROOT",
    "DEFAULT_ROUTER_STATE_EMBED_DIM",
    "DEFAULT_ROUTER_TYPE",
    "DEFAULT_SEED",
    "DEFAULT_SKILL_ROOT",
    "ROUTER_IMPL_HARD_TOP1",
    "ROUTER_IMPL_LORA_CONTROL",
    "SUPPORTED_ROUTER_TYPES",
    "MAX_ACTION_DIM",
    "MAX_STATE_DIM",
]
